### PR TITLE
Allow space characters in SimpleName.

### PR DESCRIPTION
**Pull request by skvadrik**
DEX format allows Unicode space characters in SimpleName since version 040.
Allowed space characters include everything in Unicode category 'Zs':

  0x20, 0xa0, 0x1680, 0x2000..0x200a, 0x202f, 0x205f, 0x3000

Smali now supports symtax `method with spaces` (spaces are allowed in
backtick-quoted names).

### CODE REVIEW

**Comment by skvadrik** [comment]
Just to clarify, the change in DEX format is not in the android open-source tree yet, but it will land soon. I thought it would be nice if smali allowed to construct such names as well. Backtick syntax is borrowed from kotlin (see e.g. [this issue](https://discuss.kotlinlang.org/t/android-issue-with-backticked-method-names/66) for motivation).

**Comment by skvadrik** [comment]
@JesusFreke Right, this makes sense. I will amend the patch and resubmit. We can't be sure about the API version now, but 30 seems like a fair guess to me.

**Comment by Lanchon** [comment]
> the new syntax should only be enabled if smali is assembling a version 40
file

if you allow me the comment, i think that's not good.

i haven't looked at the code, but if new syntax and/or quoting is
introduced into smali, it should be valid for dex versions. when smaling
for dex < 040, spaces should be rejected. but syntax should be the same for
all versions and quoting should be accepted.

**Comment by JesusFreke** [comment]
Yeah, that's a fair point. The quoting itself can be applicable to all versions, it's just the spaces in SimpleName that needs to be rejected on < 40

**Comment by Lanchon** [comment]
then maybe spaces whould be rejected during dex writing, which has access to dex version, and smali reading should be dex version agnostic.

**Comment by skvadrik** [comment]
Updated the patch to check the API level. I added a new field to `smaliFlexLexer` (passed as an argument to constructor). In the test I pass level 10000 (the default magic constant for "future" level).

**Comment by skvadrik** [comment]
Change landed in ART: https://android.googlesource.com/platform/art/+/ab5f4c17a86b8c808dba862db566f0ffa1146367

**Comment by skvadrik** [comment]
@JesusFreke any followup on this? Is the updated patch better?

**Comment by JesusFreke** [comment]
Sorry for the delay, I was able to take a look at this today. I noticed that there are some issues around using quoted names in a class descriptor, e.g. L`java`/`lang`/`Object`;

I've started some work to expand on your initial implementation to better handle this case, and will likely get it finished and committed (including your 2 commits here) early next week.

Thanks!

**Comment by skvadrik** [comment]
@JesusFreke great, thank you!

**Comment by JesusFreke** [comment]
This has been merged

thanks again!

**Pull request closed without merging**
