### PR TITLE
 Split JCommander utilities into a new subproject

### PR DESCRIPTION
**Pull request by Lanchon**
This frees dexlib2 from having JCommander as a transitive dependency.

### CODE REVIEW

**Comment by Lanchon** [comment]
note that JCommander is the only dependency that makes dexlib2 require Java 8.

**Comment by Lanchon** [comment]
also note that this adds a new public artifact, but there seems to be no better way out of the issue.

btw, since you are merging i'll prepare a couple more merge requests for you to consider for 2.2.5.

**Comment by JesusFreke** [comment]
I was thinking maybe merging most of utils stuff directly into dexlib2, and only leaving the stuff that smali/baksmali depend on, but not dexlib2. Thoughts?

**Comment by Lanchon** [comment]
that was a simpler change that i considered. in fact i went through the classes in util to see which are needed. result: a big bunch of them are needed. also there are some related util classes of which only some are used in dexlib2. but due to their close relatedness, all should be moved into dexlib2 (which is somewhat ugly).

also, if someone is depending on util, you'll break them.

FWIW, after seeing the result of my exercise, i thought a new package was the better option.

**Comment by JesusFreke** [comment]
Done via a different approach in https://github.com/JesusFreke/smali/pull/627

**Pull request closed without merging**
