### PR TITLE
smali/dexlib: deal with invoke-polymorphic / invoke-polymorphic/range.

### PR DESCRIPTION
**Pull request by narayank**
- Introduces two new instruction formats, 45cc and 4rcc. As the name suggests,
  these instructions are similar to 35c and 3rc, expect that they encode an
  additional constant pool reference in their 4th byte.

- Introduce two new instructions, invoke-polymorphic and
  invoke-polymorphic/range - used to implement signature polymorphism.

- Allow instructions to directly reference the proto_id section of the
  dex file. This involves the introduction of a new kind of reference
  (MethodProtoReference) and has the side effect of cleaning up a fair
  amount of special casing in ProtoPool.

- Disable support for ART version based switches (and remove LambdaTest
  which depends on it). Experimental lambda support and support for ART
  version based switches will be removed in a follow up change.

Bug: 30550796
Test: test-art
Test: ./gradlew build

### CODE REVIEW

**Comment by narayank** [comment]
I have a couple of follow ups incoming : 
 - Removing experimental lambda support from smali.
 - Adding an end to end unit test based on the test in ART. I was waiting to firm up the ART test before adding one here.

Thanks for reviewing !

**Comment by JesusFreke** [comment]
Do you want me to wait for the other changes before merging this?

**Comment by narayank** [comment]
Up to you. This change is self-contained; it doesn't break any tests and is fully functional.

**Comment by narayank** [comment]
I've updated this pull request with an additional commit that removes the experimental lambda feature.

This seems like a good point to merge this PR if you're happy with it.

**Comment by ale5000-git** [comment]
@narayank: Sorry I haven't found a way to contact you so I'm writing here.
I'm not so expert at this but I have read "has the side effect of cleaning up a fair amount of special casing in ProtoPool".
It is possibile that it reduce the methods count of the extracted file and so reduce the 65536 methods limit problem?

**Comment by narayank** [comment]
This change should make no difference to the number of methods / prototypes in the resulting dex file.

**Comment by JesusFreke** [comment]
For future reference, the review for this happened at: https://android-review.googlesource.com/#/c/254080/

**Pull request merged**
