### PR TITLE
Allow writing of dex files specifying api level and experimental flag

### PR DESCRIPTION
**Pull request by Lanchon**
fixes https://github.com/JesusFreke/smali/issues/439

### CODE REVIEW

**Comment by Lanchon** [comment]
this can introduce a regression: if someone calls DexFileFactory.writeDexFile() with a DexFile that returns null from getOpcodes(), a NPE will be thrown. of course getOpcodes() is defined @Nonnull, but still worth mentioning.

**Comment by JesusFreke** [comment]
FYI, I already have most (all?) of this fixed in 2.2. I'll see if I can go ahead and at least push what I have locally to the v2.2_WIP branch, so we're not duplicating effort.

**Comment by Lanchon** [comment]
ok, i'm very sorry. this is the first time i do a pull request on github and i wasn't aware that the pull was "live" in that later commits to the branch would be automatically added. i did it from master, so all my followup commits will show here, and the target branch cannot be changed.

this is a disaster lol !! i'll close this pull request now. and it seems you don't need a proper clone of this either.

**Comment by Lanchon** [comment]
regarding the 2.2 WIP:

i want to release my tool soon, so i'll keep on being based on stable 2.1.3. i'll change as little as possible (except if i find bugs), but i'll implement very minimum multidex support on 2.1.3.

you can later choose to merge multidex changes to 2.2, because i think you are working on orthogonal things and changes will be minimal. thanks!

**Comment by JesusFreke** [comment]
Sounds good :)

**Pull request closed without merging**
