### PR TITLE
added support for Rewriting instruction 45cc and METHOD_PROTO

### PR DESCRIPTION
**Pull request by sriteja777**

### CODE REVIEW

**Comment by sriteja777** [comment]
@JesusFreke Can you please review the PR?

**Comment by andvgal** [comment]
See also https://github.com/JesusFreke/smali/pull/818

**Comment by andvgal** [comment]
@sriteja777 you have basically taken my changes and overwritten the commit authorship

**Comment by sriteja777** [comment]
@andvgal, sorry for that. I had a problem with an app, then your PR #818 helped me to solve that to some extent. Then I have made some changes on top of it. As I can't push those changes to your PR, I created a new PR for it. I had no intention to overwritten the commit authorship.

Let me know if there is any way to preserve the ownership :)

**Comment by andvgal** [comment]
@sriteja777 you can take the latest master, cherry-pick my change and then rebase this PR on top of such branch. Then my commit should be there right before yours.

**Comment by JesusFreke** [comment]
Looks good. Thanks! Sorry for the delay!

**Pull request merged**
