### PR TITLE
Fixing METHOD_PROTO and DualReferenceInstruction writing via DexPool/ClassPool

### PR DESCRIPTION
**Pull request by andvgal**
If some class with methods which use invoke-polymorphic is rewritten via dexlib2 then it leads to exception.

The cause of missing reference in pool is self-explanatory from the changes.

Related: https://github.com/JesusFreke/smali/issues/538#issuecomment-318557593

### CODE REVIEW

**Comment by andvgal** [comment]
@JesusFreke would you have chance to review, merge and release that?

**Comment by andvgal** [comment]
Hi @JesusFreke @Lanchon . Is there any chance you would look into this PR?

**Comment by JesusFreke** [comment]
I think these changes were all merged as part of your other PR.

**Comment by andvgal** [comment]
@JesusFreke unfortunately, that commit has broken authorship trail. Please fix that, if the original author was not able to.

**Comment by JesusFreke** [comment]
Oh, sorry. I thought that was your PR for some reason. I'll see if I can fix it up, and do a history rewrite and forced push.

**Comment by JesusFreke** [comment]
Ok, history rewritten :) Hopefully nobody synced in the meantime. heh

**Comment by andvgal** [comment]
Thank you very much!

**Pull request closed without merging**
