### PR TITLE
Remove usages of the deprecated Iterators.emptyIterator() method

### PR DESCRIPTION
**Pull request by JesusFreke**

### CODE REVIEW

**Comment by kluever** [comment]
Any reason you can't go with ImmutableSet.of().iterator() instead of creating a whole new class?

**Comment by JesusFreke** [comment]
Hmm, does that return a singleton ImmutableSet and iterator? This is likely to be used many times for a typical dex file, so I was trying to reduce the number of needless object creations. But if ImmutableSet.of() and the subsequent call to iterator() are already returning singletons, then I have no objections

**Comment by kluever** [comment]
Yep, it returns a singleton. Ironically, we *just* had a request for us to clarify that documentation!

https://github.com/google/guava/issues/2083

**Comment by JesusFreke** [comment]
Great, thanks! I've updated the change to use ImmutableSet.of().iterator() instead

**Comment by kluever** [comment]
LGTM

**Pull request merged**
