### PR TITLE
Update Gradle wrapper to 3.1

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates Gradle wrapper to `2.14.1`

### CODE REVIEW

**Comment by friederbluemle** [comment]
Updated to `2.14.1` and rebased - @JesusFreke Any chance you could merge this?

**Comment by friederbluemle** [comment]
Rebased and updated again. Gradle `3.1` has been released.

**Comment by JesusFreke** [comment]
Oh, sorry. I had missed this pull request somehow. I'll get this merged this evening

**Comment by friederbluemle** [comment]
@JesusFreke Thanks

**Comment by JesusFreke** [comment]
This has been manually merged, with a few small tweaks

**Pull request closed without merging**
