### PR TITLE
IDEA-U since 2016.2 miss API getStubOrPsiParent change to getParent

### PR DESCRIPTION
**Pull request by chenjingxiong**
as title.

### CODE REVIEW

**Comment by ale5000-git** [comment]
This shouldn't be no longer needed.

**Comment by ale5000-git** [comment]
@chenjingxiong
This should be no longer needed.

Ref: https://github.com/JesusFreke/smali/commit/1390c6cff68803dd82e4939a8e0cdddc690a6502

**Comment by chenjingxiong** [comment]
Thanks.
chen jingxiong

发件人: ale5000<mailto:notifications@github.com>
发送时间: 2017年3月25日 7:46
收件人: JesusFreke/smali<mailto:smali@noreply.github.com>
抄送: chenjingxiong<mailto:chenjingxiong@gmail.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [JesusFreke/smali] IDEA-U since 2016.2 miss API getStubOrPsiParent change to getParent (#477)


@chenjingxiong<https://github.com/chenjingxiong>
This should be no longer needed.

Ref: 1390c6c<https://github.com/JesusFreke/smali/commit/1390c6cff68803dd82e4939a8e0cdddc690a6502>

―

**Comment by JesusFreke** [comment]
I think this change is now unneeded, these have all be updated.

**Pull request closed without merging**
