### PR TITLE
Refactor most of the utility classes from util into dexlib2

### PR DESCRIPTION
**Pull request by JesusFreke**
Now, util only contains the utilities that are needed by smali/baksmali,
but not dexlib2. E.g. the common command line parsing utilities, some path
utilities, etc.

This also reverses the dependency between the util module and dexlib2.

### CODE REVIEW

**Comment by JesusFreke** [comment]
@Lanchon This seems like a reasonable approach to me. What do you think?

Re: your concern about breaking existing users of util, since util now depends on dexlib2, and all* (ok, most  :)) of the classes are in the same package, I think this shouldn't affect most users. Although there are a few classes that were moved to a different package/location, where it made sense to do so.

**Comment by JesusFreke** [comment]
There actually is a rationale. The dexlib2.util stuff is mostly utilities specifically related to dex files, etc. While the stuff in util is more general purpose utilities. e.g. That's why I put something like AlignmentUtils into dexlib2.util instead of util.

**Comment by JesusFreke** [comment]
re: "non-transitive compile scope", I assume you're talking about, e.g. https://blog.gradle.org/introducing-compile-only-dependencies?

Assuming so, I can't see how that would work. If there was, e.g. an internal-util module that dexlib2 had a compile-only dependency on, dexlib2 would compile file, but the internal-util classes just wouldn't be present, and so anyone attempting to use dexlib2 would have to provide their own implementation of those classes.

Maybe I'm missing something though?

**Comment by Lanchon** [comment]
as i said, anything is better than having JCommander as an unnecessary dependency.

but if i were doing it, as a matter of taste i would choose a different solution. i wouldn't like clients to see classes that are implementation details mix in with util classes they are supposed to use. the ...internal solution is good enough.

and now that the util artifact only serves (bak)smali, i would change its name, maybe to `smali-utils`. if they are all implementation utils, i would import that package into the `implementation` configuration of (bak)smali (see https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation).

**Comment by Lanchon** [comment]
re: "non-transitive compile scope", please see the link in comment above.

**Comment by JesusFreke** [comment]
Yeah, I was considering renaming it as well. I'll have to take a look at the java-library plugin. The separate implementation vs. api configurations do sound useful.

**Comment by Lanchon** [comment]
`compile` configuration is deprecated. `api` is what compile was before, and `implementation` is a compile and runtime dependency that is not exposed to clients of dexlib2 during their compilation (so you cannot use the dependency except through reflection).

**Comment by Lanchon** [comment]
android has the same thing: classes that are actually accessible in the runtime classpath of apps but hidden from the compile classpath. gradle has this per-dependency mechanism we talked about to similar effect, and also plans to add a per-class mechanism.

it's a shame that some of these kluges are needed because java designers did not include a C++-style "friend" feature, and overloaded the function of packages instead.

**Comment by JesusFreke** [comment]
Yeah, I'll look more into splitting out the internal classes. Hopefully when gradle supports distinguishing on a per-class basis. It'll probably be done as a more major restructuring as part of a major release.

**Comment by Lanchon** [comment]
maybe do this asap, lessens the chance of breaking clients. of course when in doubt, make it internal.

**Comment by Lanchon** [comment]
> as part of a major release

so you are back on smali, yay!! i hope whatever made you temporarily unavailable before was a good thing :)

**Comment by JesusFreke** [comment]
It's mostly just a matter of personal motivation :) Been busy with other projects and haven't had much motivation to do much on smali ;)

**Pull request merged**
