### PR TITLE
Art

### PR DESCRIPTION
**Pull request by HomerSp**
This adds full ART/OAT support in baksmali (for deodexing). Feel free to use this code as you wish, and if you have any questions regarding the code, ask away :)

Some parts of the code, like ensureCanCallMethod of MethodAnalyzer, is not strictly related to ART, but are things I discovered while deodexing older odexes.

There are also some parts I had to rewrite because it wasn't working properly in ART, but I have tested deodexing both OAT files and regular odex files, and they seem to deodex just fine.

### CODE REVIEW

**Comment by JesusFreke** [comment]
I haven't looked at the code yet, but how are you handling field offsets? From my investigations, they are currently not well specified, and may be dependent on the specific implementation-specific behavior of the c++ runtime on the device (e.g. a non-stable sort, and a non-stable priority_queue). 

There are recent changes to art to fix this, but those changes aren't in any released version of android yet.

**Comment by HomerSp** [comment]
@JesusFreke I am merely skipping over any fields with names that start with shadow$_ (which includes shadow$_klass_ and shadow$_monitor_). This has worked on every rom I've tried it on (HTC One, LG G3 and G2, various Samsung devices, Nexus devices), but this may have to be rewritten when a new version of android hits (I haven't looked into how future versions do this).
I had major problems getting this to work properly initially, I recall that an earlier method worked on my One, but not on the G3. So I came up with this idea, it may not be the best, but it does seem to work.
As for the fields themselves, they appear to be sorted, first references, then wide fields and last others. So I am merely adding them to separate lists, sorting them, and then merging them to a big list. I don't know if this is the best way to do it, but yet again, it works :)

**Comment by JesusFreke** [comment]
I'm not talking about shadow$_ fields. In some cases, the order of the fields isn't well specified. For example, if there is a short and a char field that have the same name, then the order of those 2 fields with respect to each other is not well defined, because an unstable sort is used, and both fields are "equal" for the comparison that's used for sorting.

So, you would have to implement the *exact* same sorting algorithm that is used on the device. And every device could potentially have a different implementation of the sorting algorithm.

And there's another similar thing, where the field gaps are tracked using a priority_queue, but in some cases, there can be multiple "equal" gaps in the priority_queue, and it's not well defined which gap should be filled first.

For example, here are the relevant changes that fix these problems, although these changes aren't live on any device yet.
https://android-review.googlesource.com/#/c/114281/
https://android-review.googlesource.com/#/c/114814/
https://android-review.googlesource.com/#/c/133351/

These were the main reasons that I decided not to implement support for art odexes for now. In order to handle these cases properly, you would need a device-side component that would link against art and determine the correct field offsets .

**Comment by HomerSp** [comment]
Thank you for the explanation, I wasn't aware of that. I guess I have been lucky it has worked as well as it has (no problems whatsoever on the devices I have tried), have you ran into these problems yourself on any devices?
I haven't seen any fields with the same name on any of my tests, but since that's possible, and the order of them is unknown this would indeed be quite a big problem.

**Comment by JesusFreke** [comment]
Various obfuscators (including proguard) will often rename fields so that there are multiple fields with the same name but different types. And the priority_queue one can be triggered by certain field layouts that can occur even in non-obfuscated code.

**Comment by JesusFreke** [comment]
baksmali now supports ART oat files for M+

**Pull request closed without merging**
